# Generated by Django 4.1.4 on 2025-02-04 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ChineseFlashcard',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('chinese', models.CharField(max_length=100)),
                ('pinyin', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=255)),
                (
                    'next_review',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ('correct', models.IntegerField(default=0)),
                ('incorrect', models.IntegerField(default=0)),
            ],
        ),
    ]
