# Generated by Django 4.1.4 on 2025-02-04 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChineseFlashcard',
            new_name='Flashcard',
        ),
    ]
