# Generated by Django 5.1.5 on 2025-02-11 21:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('flashcards', '0002_rename_chineseflashcard_flashcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('character', models.CharField(max_length=10)),
                ('pinyin', models.CharField(max_length=50)),
                ('translation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'next_review',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ('consecutive_correct', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='decks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='Flashcard',
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cards',
                to='flashcards.deck',
            ),
        ),
    ]
