# Generated by Django 5.1.5 on 2025-02-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_card_deck_delete_flashcard_card_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
